"""Remove unwanted columns from application table

Revision ID: 0b051a504f2d
Revises:
Create Date: 2026-07-13 17:22:24.961155

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0b051a504f2d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.drop_column("status")
        batch_op.drop_column("applied_on")
        batch_op.drop_column("notes")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notes", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("applied_on", sa.TIMESTAMP(), nullable=False))
        batch_op.add_column(sa.Column("status", sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
