"""Remove template_id from Document table

Revision ID: 20d90f4f3029
Revises: 0b051a504f2d
Create Date: 2026-07-13 17:23:56.384189

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20d90f4f3029"
down_revision = "0b051a504f2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column("template_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("template_id", sa.VARCHAR(length=36), nullable=False)
        )
        batch_op.create_foreign_key(None, "template", ["template_id"], ["template_id"])

    # ### end Alembic commands ###
