"""Remove template table

Revision ID: 2df3da62467c
Revises: 20d90f4f3029
Create Date: 2026-07-13 17:32:01.342528

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2df3da62467c"
down_revision = "20d90f4f3029"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("template")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template",
        sa.Column("template_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("doc_type", sa.TEXT(), nullable=False),
        sa.Column("country_code", sa.VARCHAR(length=10), nullable=False),
        sa.Column("template_content", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("template_id"),
    )
    # ### end Alembic commands ###
