"""Remove the onboarding_completed coloumn from the user table

Revision ID: 68184920d746
Revises: 8448ff6e7d05
Create Date: 2026-08-05 12:26:35.529120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68184920d746'
down_revision = '8448ff6e7d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('onbaording_completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onbaording_completed', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
