"""Use JSON columns for matching skills and job description

Revision ID: 8448ff6e7d05
Revises: f367bcbdb8ca
Create Date: 2026-07-14 01:05:42.335453

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8448ff6e7d05"
down_revision = "f367bcbdb8ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_entry", schema=None) as batch_op:
        batch_op.alter_column(
            "matching_skills",
            existing_type=sa.TEXT(),
            type_=sa.JSON(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "job_description",
            existing_type=sa.TEXT(),
            type_=sa.JSON(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_entry", schema=None) as batch_op:
        batch_op.alter_column(
            "job_description",
            existing_type=sa.JSON(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "matching_skills",
            existing_type=sa.JSON(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
