"""Add user_personal table

Revision ID: 84ff8c6bef60
Revises: a225c57f4ee0
Create Date: 2026-07-13 22:25:46.431740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ff8c6bef60'
down_revision = 'a225c57f4ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_personal',
    sa.Column('user_personal_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('phone_number', sa.TEXT(), nullable=False),
    sa.Column('city', sa.TEXT(), nullable=False),
    sa.Column('country', sa.TEXT(), nullable=False),
    sa.Column('linkedin_url', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_personal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_personal')
    # ### end Alembic commands ###
