"""Remove question table

Revision ID: a225c57f4ee0
Revises: b4a1b1baa21f
Create Date: 2026-07-13 17:34:25.061113

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a225c57f4ee0"
down_revision = "b4a1b1baa21f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("question_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("question_text", sa.TEXT(), nullable=False),
        sa.Column("category", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("question_id"),
    )
    # ### end Alembic commands ###
