"""Remove practice_answer table

Revision ID: b4a1b1baa21f
Revises: 2df3da62467c
Create Date: 2026-07-13 17:33:10.714135

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b4a1b1baa21f"
down_revision = "2df3da62467c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("practice_answer")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_answer",
        sa.Column("practice_answer_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("question_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("user_answer", sa.TEXT(), nullable=False),
        sa.Column("ai_suggested_answer", sa.TEXT(), nullable=True),
        sa.Column("tone_feedback", sa.TEXT(), nullable=True),
        sa.Column("clarity_feedback", sa.TEXT(), nullable=True),
        sa.Column("impact_feedback", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.question_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("practice_answer_id"),
    )
    # ### end Alembic commands ###
