"""remove  job_decripton column to job_entry table

Revision ID: ceaa200abe35
Revises: f5927e664c84
Create Date: 2026-07-14 00:55:34.558425

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ceaa200abe35"
down_revision = "f5927e664c84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_entry", schema=None) as batch_op:
        batch_op.drop_column("job_descripton")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_descripton", sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
