"""add  job_decription column to job_entry table

Revision ID: f367bcbdb8ca
Revises: ceaa200abe35
Create Date: 2026-07-14 00:57:18.694799

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f367bcbdb8ca"
down_revision = "ceaa200abe35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_description", sa.TEXT(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_entry", schema=None) as batch_op:
        batch_op.drop_column("job_description")

    # ### end Alembic commands ###
