"""Remove due_date coloumn from job_entry table

Revision ID: f5927e664c84
Revises: 84ff8c6bef60
Create Date: 2026-07-13 23:45:10.580623

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f5927e664c84"
down_revision = "84ff8c6bef60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_entry", schema=None) as batch_op:
        batch_op.drop_column("due_date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("due_date", sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
